<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="0" total="11" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="100704" started-at="2020-02-25T17:36:35Z" finished-at="2020-02-25T17:38:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="100704" started-at="2020-02-25T17:36:35Z" finished-at="2020-02-25T17:38:16Z">
      <class name="testcases.Module9_1">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="startBrowser" is-config="true" duration-ms="6449" started-at="2020-02-25T17:36:35Z" finished-at="2020-02-25T17:36:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="3371" started-at="2020-02-25T17:36:42Z" data-provider="getTestData" finished-at="2020-02-25T17:36:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Click on Login Button]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[css]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input[id^='u_0'][value='Log In']]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at functions.UIOperation.perform(UIOperation.java:117)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6617" started-at="2020-02-25T17:36:46Z" finished-at="2020-02-25T17:36:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="3092" started-at="2020-02-25T17:36:52Z" data-provider="getTestData" finished-at="2020-02-25T17:36:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Navigate back to Facebook page]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[NAVIGATEBACK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6626" started-at="2020-02-25T17:36:55Z" finished-at="2020-02-25T17:37:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=SUCCESS method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="2131" started-at="2020-02-25T17:37:02Z" data-provider="getTestData" finished-at="2020-02-25T17:37:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Click on SignUp Button]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[(//button[text()='Sign Up'])[1]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at functions.UIOperation.perform(UIOperation.java:110)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6695" started-at="2020-02-25T17:37:04Z" finished-at="2020-02-25T17:37:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="1798" started-at="2020-02-25T17:37:11Z" data-provider="getTestData" finished-at="2020-02-25T17:37:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Check the error message 2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[//input[@aria-label='First name']]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at functions.UIOperation.perform(UIOperation.java:110)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6579" started-at="2020-02-25T17:37:13Z" finished-at="2020-02-25T17:37:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="340" started-at="2020-02-25T17:37:19Z" data-provider="getTestData" finished-at="2020-02-25T17:37:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Validate the error message 2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[GETTEXTVALIDATION]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[(//div[@class='_5633 _5634 _53ij'])[1]]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[What's your name?]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.support.ui.UnexpectedTagNameException">
            <message>
              <![CDATA[Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.<init>(Select.java:48)
at functions.UIOperation.perform(UIOperation.java:144)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.support.ui.UnexpectedTagNameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6738" started-at="2020-02-25T17:37:20Z" finished-at="2020-02-25T17:37:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="1952" started-at="2020-02-25T17:37:26Z" data-provider="getTestData" finished-at="2020-02-25T17:37:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Check the error message 3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[//input[@aria-label='Mobile number or email address']]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6683" started-at="2020-02-25T17:37:28Z" finished-at="2020-02-25T17:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=SUCCESS method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="254" started-at="2020-02-25T17:37:35Z" data-provider="getTestData" finished-at="2020-02-25T17:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Validate the error message 3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[GETTEXTVALIDATION]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[(//div[@class='_5633 _5634 _53ij'])[2]]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[You'll use this when you log in and if you ever need to reset your password.]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.support.ui.UnexpectedTagNameException">
            <message>
              <![CDATA[Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.<init>(Select.java:48)
at functions.UIOperation.perform(UIOperation.java:144)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.support.ui.UnexpectedTagNameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6600" started-at="2020-02-25T17:37:35Z" finished-at="2020-02-25T17:37:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="1819" started-at="2020-02-25T17:37:42Z" data-provider="getTestData" finished-at="2020-02-25T17:37:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Check the error message 4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[//input[@aria-label='New password']]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6600" started-at="2020-02-25T17:37:44Z" finished-at="2020-02-25T17:37:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=SUCCESS method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="320" started-at="2020-02-25T17:37:50Z" data-provider="getTestData" finished-at="2020-02-25T17:37:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Validate the error message 4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[GETTEXTVALIDATION]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[(//div[@class='_5633 _5634 _53ij'])[3]]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Enter a combination of at least six numbers, letters and punctuation marks (such as ! and &).]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.support.ui.UnexpectedTagNameException">
            <message>
              <![CDATA[Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.<init>(Select.java:48)
at functions.UIOperation.perform(UIOperation.java:144)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.support.ui.UnexpectedTagNameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6684" started-at="2020-02-25T17:37:51Z" finished-at="2020-02-25T17:37:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="1864" started-at="2020-02-25T17:37:57Z" data-provider="getTestData" finished-at="2020-02-25T17:37:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Check the error message 5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CLICK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[(//i)[18]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6649" started-at="2020-02-25T17:37:59Z" finished-at="2020-02-25T17:38:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=SUCCESS method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="negativeScenariosTest" duration-ms="285" started-at="2020-02-25T17:38:06Z" data-provider="getTestData" finished-at="2020-02-25T17:38:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Validate the error message 5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[GETTEXTVALIDATION]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[(//div[@class='_5633 _5634 _53ij'])[4]]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xpath]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Please choose a gender. You can change who can see this later.]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.support.ui.UnexpectedTagNameException">
            <message>
              <![CDATA[Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "div"
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHIRAJ-LAPTOP', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.<init>(Select.java:48)
at functions.UIOperation.perform(UIOperation.java:144)
at testcases.Module9_1.negativeScenariosTest(Module9_1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.support.ui.UnexpectedTagNameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenariosTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="tearDown" is-config="true" duration-ms="6632" started-at="2020-02-25T17:38:06Z" finished-at="2020-02-25T17:38:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=negativeScenariosTest on [Module9_1 passed=0 failed=0 skipped=0] status=FAILURE method=Module9_1.negativeScenariosTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="closeBrowser()[pri:0, instance:[Module9_1 passed=0 failed=0 skipped=0]]" name="closeBrowser" is-config="true" duration-ms="3057" started-at="2020-02-25T17:38:13Z" finished-at="2020-02-25T17:38:16Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[javax.mail.MessagingException: IOException while sending message;
  nested exception is:
java.io.FileNotFoundException: F:\JAVA\Selenium\EclipsePhotonProjects\PallaviAssignment\Reports\TestReport.html (The system cannot find the file specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
java.io.FileNotFoundException: F:\JAVA\Selenium\EclipsePhotonProjects\PallaviAssignment\Reports\TestReport.html (The system cannot find the file specified)
at functions.SendTestReportInEmail.send(SendTestReportInEmail.java:87)
at testcases.Module9_1.closeBrowser(Module9_1.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
java.io.FileNotFoundException: F:\JAVA\Selenium\EclipsePhotonProjects\PallaviAssignment\Reports\TestReport.html (The system cannot find the file specified)
at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
at javax.mail.Transport.send0(Transport.java:255)
at javax.mail.Transport.send(Transport.java:124)
at functions.SendTestReportInEmail.send(SendTestReportInEmail.java:81)
... 25 more
Caused by: java.io.FileNotFoundException: F:\JAVA\Selenium\EclipsePhotonProjects\PallaviAssignment\Reports\TestReport.html (The system cannot find the file specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
at javax.activation.DataHandler.writeTo(DataHandler.java:305)
at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1652)
at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
at javax.activation.DataHandler.writeTo(DataHandler.java:317)
at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1652)
at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testcases.Module9_1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
